// app/layout.tsx (Root Layout)
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css'; // Import global CSS here

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* You can add shared components here, e.g., <Header />, <Footer /> */}
        {children}
      </body>
    </html>
  );
}
